module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'chore',
        'ci',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'core',
        '3d',
        'ui',
        'auth',
        'quiz',
        'api',
        'deps',
        'config',
        'layout',
      ],
    ],
    'subject-case': [2, 'never', ['sentence-case']],
    'subject-empty': [2, 'never'],
    'subject-max-length': [2, 'always', 100],
    'body-max-line-length': [2, 'always', 200],
    'footer-max-line-length': [2, 'always', 200],
  },
}
