import { Constellation } from "@/types/canvas/constellation";

export const CONSTELLATIONS: Constellation[] = [
  {
    id: "orion",
    name: "Orion",
    indonesianName: "Belantik",
    description:
      "Rasi yang paling dikenal di langit malam, terlihat jelas dari Belahan Bumi Utara maupun Selatan.",
    mythology:
      "Dalam mitologi Yunani, Orion adalah pemburu legendaris yang dikejar oleh kalajengkin Scorpius. Zeus menempatkan mereka di sisi berlawanan langit agar tidak pernah bertemu.",
    bestViewing: "Desember - Maret",
    stars: [
      {
        id: "betelgeuse",
        name: "Betelgeuse",
        magnitude: 0.42,
        type: "supergiant",
        color: "#ffcc6f",
        x: 0.15,
        y: 0.2,
      },
      {
        id: "rigel",
        name: "Rigel",
        magnitude: 0.13,
        type: "supergiant",
        color: "#aabfff",
        x: 0.25,
        y: 0.35,
      },
      {
        id: "bellatrix",
        name: "Bellatrix",
        magnitude: 1.64,
        type: "giant",
        color: "#cad8ff",
        x: 0.22,
        y: 0.22,
      },
      {
        id: "saiph",
        name: "Saiph",
        magnitude: 2.06,
        type: "supergiant",
        color: "#aabfff",
        x: 0.2,
        y: 0.38,
      },
      {
        id: "alnitak",
        name: "Alnitak",
        magnitude: 1.77,
        type: "supergiant",
        color: "#aabfff",
        x: 0.17,
        y: 0.28,
      },
      {
        id: "alnilam",
        name: "Alnilam",
        magnitude: 1.69,
        type: "supergiant",
        color: "#cad8ff",
        x: 0.195,
        y: 0.27,
      },
      {
        id: "mintaka",
        name: "Mintaka",
        magnitude: 2.23,
        type: "giant",
        color: "#cad8ff",
        x: 0.22,
        y: 0.26,
      },
    ],
    lines: [
      { from: "betelgeuse", to: "bellatrix" },
      { from: "bellatrix", to: "mintaka" },
      { from: "mintaka", to: "alnilam" },
      { from: "alnilam", to: "alnitak" },
      { from: "alnitak", to: "saiph" },
      { from: "saiph", to: "rigel" },
      { from: "rigel", to: "betelgeuse" },
    ],
    center: { x: 0.2, y: 0.28 },
  },
  {
    id: "ursa-major",
    name: "Ursa Major",
    indonesianName: "Biduk / Bintang Utara",
    description:
      'Rasi terbesar ketiga di langit. Mengandung Asterism "Big Dipper" yang terkenal.',
    mythology:
      "Dalam mitologi Yunani, Ursa Major adalah Callisto yang diubah menjadi beruang oleh Hera, lalu ditempatkan di langit oleh Zeus.",
    bestViewing: "Maret - Juni",
    stars: [
      {
        id: "dubhe",
        name: "Dubhe",
        magnitude: 1.79,
        type: "giant",
        color: "#ffd2a1",
        x: 0.6,
        y: 0.15,
      },
      {
        id: "merak",
        name: "Merak",
        magnitude: 2.37,
        type: "main-sequence",
        color: "#cad8ff",
        x: 0.55,
        y: 0.18,
      },
      {
        id: "phecda",
        name: "Phecda",
        magnitude: 2.44,
        type: "main-sequence",
        color: "#cad8ff",
        x: 0.52,
        y: 0.22,
      },
      {
        id: "megrez",
        name: "Megrez",
        magnitude: 3.31,
        type: "main-sequence",
        color: "#cad8ff",
        x: 0.55,
        y: 0.2,
      },
      {
        id: "alioth",
        name: "Alioth",
        magnitude: 1.77,
        type: "main-sequence",
        color: "#cad8ff",
        x: 0.58,
        y: 0.19,
      },
      {
        id: "mizar",
        name: "Mizar",
        magnitude: 2.27,
        type: "main-sequence",
        color: "#cad8ff",
        x: 0.62,
        y: 0.18,
      },
      {
        id: "alkaid",
        name: "Alkaid",
        magnitude: 1.86,
        type: "main-sequence",
        color: "#aabfff",
        x: 0.65,
        y: 0.16,
      },
    ],
    lines: [
      { from: "dubhe", to: "merak" },
      { from: "merak", to: "phecda" },
      { from: "phecda", to: "megrez" },
      { from: "megrez", to: "alioth" },
      { from: "alioth", to: "mizar" },
      { from: "mizar", to: "alkaid" },
      { from: "megrez", to: "dubhe" },
    ],
    center: { x: 0.58, y: 0.18 },
  },
  {
    id: "cassiopeia",
    name: "Cassiopeia",
    indonesianName: "Kasiopea",
    description:
      'Rasi berbentuk "W" yang mudah dikenali, terletak di dekat Kutub Utara langit.',
    mythology:
      "Cassiopeia adalah ratu Ethiopia dalam mitologi Yunani yang sombong tentang kecantikannya. Dewa Poseidon menghukumnya dengan menempatkannya di langit terbalik.",
    bestViewing: "Oktober - Maret",
    stars: [
      {
        id: "schedar",
        name: "Schedar",
        magnitude: 2.24,
        type: "giant",
        color: "#ffd2a1",
        x: 0.4,
        y: 0.12,
      },
      {
        id: "caph",
        name: "Caph",
        magnitude: 2.27,
        type: "giant",
        color: "#fff4ea",
        x: 0.45,
        y: 0.1,
      },
      {
        id: "gamma-cas",
        name: "Gamma Cassiopeiae",
        magnitude: 2.47,
        type: "supergiant",
        color: "#aabfff",
        x: 0.38,
        y: 0.14,
      },
      {
        id: "ruchbah",
        name: "Ruchbah",
        magnitude: 2.68,
        type: "main-sequence",
        color: "#cad8ff",
        x: 0.42,
        y: 0.16,
      },
      {
        id: "segin",
        name: "Segin",
        magnitude: 3.37,
        type: "giant",
        color: "#aabfff",
        x: 0.44,
        y: 0.13,
      },
    ],
    lines: [
      { from: "caph", to: "schedar" },
      { from: "schedar", to: "gamma-cas" },
      { from: "gamma-cas", to: "ruchbah" },
      { from: "ruchbah", to: "segin" },
    ],
    center: { x: 0.42, y: 0.13 },
  },
  {
    id: "scorpius",
    name: "Scorpius",
    indonesianName: "Kalajengking",
    description:
      "Rasi yang terlihat seperti kalajengking dengan bintang merah Antares sebagai jantungnya.",
    mythology:
      "Scorpius adalah kalajengkin yang dikirim Gaia untuk membunuh Orion. Zeus menempatkan mereka di sisi berlawanan langit.",
    bestViewing: "Juni - Agustus",
    stars: [
      {
        id: "antares",
        name: "Antares",
        magnitude: 1.09,
        type: "supergiant",
        color: "#ffcc6f",
        x: 0.8,
        y: 0.6,
      },
      {
        id: "shaula",
        name: "Shaula",
        magnitude: 1.62,
        type: "supergiant",
        color: "#aabfff",
        x: 0.85,
        y: 0.75,
      },
      {
        id: "sargas",
        name: "Sargas",
        magnitude: 1.87,
        type: "giant",
        color: "#fff4ea",
        x: 0.82,
        y: 0.7,
      },
      {
        id: "dschubba",
        name: "Dschubba",
        magnitude: 2.32,
        type: "supergiant",
        color: "#aabfff",
        x: 0.78,
        y: 0.55,
      },
      {
        id: "graffias",
        name: "Graffias",
        magnitude: 2.62,
        type: "giant",
        color: "#aabfff",
        x: 0.75,
        y: 0.52,
      },
    ],
    lines: [
      { from: "graffias", to: "dschubba" },
      { from: "dschubba", to: "antares" },
      { from: "antares", to: "sargas" },
      { from: "sargas", to: "shaula" },
    ],
    center: { x: 0.8, y: 0.62 },
  },
  {
    id: "leo",
    name: "Leo",
    indonesianName: "Singa",
    description:
      "Rasi yang menyerupai singa, dengan bintang Regulus sebagai jantung singa.",
    mythology:
      "Leo adalah Nemean Lion yang dikalahkan Hercules sebagai salah satu dari 12 petualangannya. Zeus menempatkannya di langit untuk menghormati kemenangan Hercules.",
    bestViewing: "Maret - Mei",
    stars: [
      {
        id: "regulus",
        name: "Regulus",
        magnitude: 1.35,
        type: "supergiant",
        color: "#aabfff",
        x: 0.35,
        y: 0.45,
      },
      {
        id: "denebola",
        name: "Denebola",
        magnitude: 2.13,
        type: "main-sequence",
        color: "#cad8ff",
        x: 0.48,
        y: 0.42,
      },
      {
        id: "algieba",
        name: "Algieba",
        magnitude: 2.28,
        type: "giant",
        color: "#ffd2a1",
        x: 0.32,
        y: 0.4,
      },
      {
        id: "zosma",
        name: "Zosma",
        magnitude: 2.56,
        type: "main-sequence",
        color: "#cad8ff",
        x: 0.42,
        y: 0.42,
      },
      {
        id: "chertan",
        name: "Chertan",
        magnitude: 3.33,
        type: "main-sequence",
        color: "#cad8ff",
        x: 0.4,
        y: 0.46,
      },
    ],
    lines: [
      { from: "regulus", to: "algieba" },
      { from: "algieba", to: "zosma" },
      { from: "zosma", to: "denebola" },
      { from: "denebola", to: "chertan" },
      { from: "chertan", to: "regulus" },
    ],
    center: { x: 0.4, y: 0.43 },
  },
  {
    id: "cygnus",
    name: "Cygnus",
    indonesianName: "Angsa",
    description:
      "Rasi yang menyerupai ansa terbang, juga dikenal sebagai Northern Cross.",
    mythology:
      "Dalam mitologi Yunani, Cygnus adalah bentuk ansa dari Zeus yang terbang menyeberangi Sungai Eurotas untuk mencari Europa.",
    bestViewing: "Juni - Oktober",
    stars: [
      {
        id: "deneb",
        name: "Deneb",
        magnitude: 1.25,
        type: "supergiant",
        color: "#fff4ea",
        x: 0.7,
        y: 0.3,
      },
      {
        id: "sadr",
        name: "Sadr",
        magnitude: 2.23,
        type: "supergiant",
        color: "#fff4ea",
        x: 0.72,
        y: 0.35,
      },
      {
        id: "gienah",
        name: "Gienah",
        magnitude: 2.46,
        type: "giant",
        color: "#ffd2a1",
        x: 0.68,
        y: 0.38,
      },
      {
        id: "albireo",
        name: "Albireo",
        magnitude: 3.08,
        type: "giant",
        color: "#ffd2a1",
        x: 0.72,
        y: 0.42,
      },
      {
        id: "fasx",
        name: "Fawaz",
        magnitude: 2.87,
        type: "giant",
        color: "#cad8ff",
        x: 0.75,
        y: 0.35,
      },
    ],
    lines: [
      { from: "deneb", to: "sadr" },
      { from: "sadr", to: "albireo" },
      { from: "sadr", to: "gienah" },
      { from: "sadr", to: "fasx" },
    ],
    center: { x: 0.72, y: 0.35 },
  },
];
